default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        # Secret files must not end with a new line character, or else the new
        # line will be included in the secret data.
        exclude: docker/dev_secrets|docker/dev_configs
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: forbid-tabs

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
        # These dependencies are needed so that the django-stubs plugin can
        # load settings.py for the myakuweb project without getting import
        # errors.
        additional_dependencies:
          - django-stubs
          - mecab-python3
          - jaconv
          - pytz
          - requests
          - celery

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
      - id: seed-isort-config
        args:
          - --application-directories=\
                myaku:\
                myakuweb/myakuweb:\
                myakuweb/search:\
                docker/mongobackup:\
                docker/myaku_run-tests

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args:
          - --check-only
          - --diff
          - --thirdparty=docker
