language: python
python: "3.7"
dist: bionic

install:
  - pip install pre-commit==1.18.3
  - ./docker/setup_scripts/ubuntu_bootstrap.sh
script:
  - pre-commit run --all-files
  - ./docker/setup_scripts/build_all_test_images.sh && ./run_tests.sh -e test

services:
  - docker
