language: python
python: "3.7"
dist: bionic

install:
  - pip install pre-commit==1.21.0
  - ./docker/setup_scripts/install_react_app_deps.sh
  - ./docker/setup_scripts/install_docker.sh
script:
  - ./docker/setup_scripts/run_pre_commit.sh
  - ./docker/setup_scripts/build_all_test_images.sh && ./run_tests.sh -e test

services:
  - docker
