# Development overrides for the Myaku stack.
# Always uses the versions tagged as latest for all images instead of fixed
# versions.
#
# Run docker stack deploy pasing both the docker-compose.yml file and this file
# as -f args to run the Myaku stack configured for development, or pass just
# the docker-compose.yml file as an -f arg to run the Myaku stack configured
# for production.

version: "3.7"
services:
  crawler:
    image: friedrice2/myaku_crawler.dev:latest
    deploy:
      restart_policy:
        condition: none
    volumes:
      - type: volume
        source: crawler_devdata
        target: /myaku/devdata

      - type: bind
        source: ..
        target: /myaku/src
    environment:
      # A cron schedule of "#" will comment out the line for the crawl job in
      # the crontab file so that it will not run while doing develpment.
      CRAWL_CRON_SCHEDULE: "#"  
      DEBUG_LOG_MAX_SIZE: 0
      INFO_LOG_MAX_SIZE: 0
  db:
    image: friedrice2/myaku_mongo.myakudb:latest
    deploy:
      restart_policy:
        condition: none
  mongobackup:
    image: friedrice2/mongobackup:latest
    deploy:
      restart_policy:
        condition: none

volumes:
  crawler_devdata:

secrets:
  db_root_username:
    file: ./test_secrets/db_root_username_TESTUSEONLY.txt
  db_root_password:
    file: ./test_secrets/db_root_password_TESTUSEONLY.txt
  db_backup_username:
    file: ./test_secrets/db_backup_username_TESTUSEONLY.txt
  db_backup_password:
    file: ./test_secrets/db_backup_password_TESTUSEONLY.txt
  db_crawler_username:
    file: ./test_secrets/db_crawler_username_TESTUSEONLY.txt
  db_crawler_password:
    file: ./test_secrets/db_crawler_password_TESTUSEONLY.txt
