# Test overrides for the Myaku stack.
# 
# By default, uses the images tagged "test" for each service. These images are
# automatically built when running run_tests.sh, and they are functionally built
# the exact same way as the prod images for each service.
#
# Run docker stack deploy passing both the docker-compose.yml file and this
# file as -f args to run the Myaku stack configured for running the test suite.

version: "3.7"
services:
  crawler:
    image: friedrice2/myaku_crawler:test
    deploy:
      restart_policy:
        condition: none
    environment:
      # A cron schedule of "#" will comment out the line for the crawl job in
      # the crontab file so that it will not run during testing.
      CRAWL_CRON_SCHEDULE: "#"  
  rescore:
    image: friedrice2/myaku_rescore:test
    deploy:
      restart_policy:
        condition: none
    environment:
      # A cron schedule of "#" will comment out the line for the rescore job in
      # the crontab file so that it will not run during testing.
      RESCORE_CRON_SCHEDULE: "#"  
  web:
    image: friedrice2/myaku_web:test
    deploy:
      restart_policy:
        condition: none
  reverseproxy:
    image: friedrice2/myaku_nginx.reverseproxy:test
    deploy:
      restart_policy:
        condition: none
  crawldb:
    image: friedrice2/myaku_mongo.crawldb:test
    deploy:
      restart_policy:
        condition: none
  crawldb_backup:
    image: friedrice2/mongobackup:test
    deploy:
      restart_policy:
        condition: none
    environment:
      # A cron schedule of "#" will comment out the line for the backup job in
      # the crontab file so that it will not run while doing development.
      DB_BACKUP_CRON_SCHEDULE: "#"

configs:
  myakuweb_allowed_hosts:
    file: ./dev_configs/myakuweb_allowed_hosts_DEVUSEONLY.txt

secrets:
  crawldb_root_username:
    file: ./dev_secrets/crawldb_root_username_DEVUSEONLY.txt
  crawldb_root_password:
    file: ./dev_secrets/crawldb_root_password_DEVUSEONLY.txt
  crawldb_backup_username:
    file: ./dev_secrets/crawldb_backup_username_DEVUSEONLY.txt
  crawldb_backup_password:
    file: ./dev_secrets/crawldb_backup_password_DEVUSEONLY.txt
  crawldb_crawler_username:
    file: ./dev_secrets/crawldb_crawler_username_DEVUSEONLY.txt
  crawldb_crawler_password:
    file: ./dev_secrets/crawldb_crawler_password_DEVUSEONLY.txt
  crawldb_web_username:
    file: ./dev_secrets/crawldb_web_username_DEVUSEONLY.txt
  crawldb_web_password:
    file: ./dev_secrets/crawldb_web_password_DEVUSEONLY.txt
  web_django_secret_key:
    file: ./dev_secrets/web_django_secret_key_DEVUSEONLY.txt
