# Test overrides for the Myaku stack.
#
# Uses the images tagged "test" for each service. These images are
# automatically built when running run_tests.sh, and they are functionally
# built the exact same way as the prod images for each service.
#
# Run docker stack deploy passing both the docker-compose.yml file and this
# file as -f args to run the Myaku stack configured for running the test suite.

version: "3.7"
services:
  crawler:
    image: friedrice2/myaku_crawler:test
    deploy:
      restart_policy:
        condition: none
  rescore:
    image: friedrice2/myaku_rescore:test
    deploy:
      restart_policy:
        condition: none
  web:
    image: friedrice2/myaku_web:test
    deploy:
      restart_policy:
        condition: none
  web-worker:
    image: friedrice2/myaku_web:test
    deploy:
      restart_policy:
        condition: none
  first-page-cache:
    image: friedrice2/myaku_redis.first-page-cache:test
    deploy:
      restart_policy:
        condition: none
  next-page-cache:
    image: friedrice2/myaku_redis.next-page-cache:test
    deploy:
      restart_policy:
        condition: none
  reverseproxy:
    image: friedrice2/myaku_nginx.reverseproxy:test
    deploy:
      restart_policy:
        condition: none
  crawldb:
    image: friedrice2/myaku_mongo.crawldb:test
    deploy:
      restart_policy:
        condition: none
  crawldb_backup:
    image: friedrice2/mongobackup:test
    deploy:
      restart_policy:
        condition: none
