# Production stack configuration for Myaku.
# Image versions are all the versions that are currently deployed in
# production.
#
# Run docker stack deploy pasing just this file as an -f arg to run the Myaku
# stack configured for production, or pass both this file and the
# docker-compose.dev.yml file as -f args to run the Myaku stack configured for
# development.

version: "3.7"
services:
  crawler:
    image: friedrice2/myaku_crawler:1.2.0
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
    volumes:
      - type: volume
        source: crawler_log
        target: /crawler/log

      - type: volume
        source: crawler_appdata
        target: /crawler/appdata

      # Needed for Firefox web driver to work reliably in the container.
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2000000000  # 2gb
    environment:
      CRAWL_CRON_SCHEDULE: "0 1,4,7,10,13,16,19,22 * * *"
      CRAWLER_LIST: "NhkNewsWeb,Kakuyomu"
      MYAKU_CRAWLDB_HOST: crawldb
      MYAKU_CRAWLDB_USERNAME_FILE: /run/secrets/crawldb_crawler_username
      MYAKU_CRAWLDB_PASSWORD_FILE: /run/secrets/crawldb_crawler_password
      DEBUG_LOG_MAX_SIZE: 200000000  # 200mb
      INFO_LOG_MAX_SIZE: 20000000 # 20mb
    secrets:
      - crawldb_crawler_username
      - crawldb_crawler_password
    networks:
      - crawler_net
  rescore:
    image: friedrice2/myaku_rescore:1.0.0
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
    volumes:
      - type: volume
        source: rescore_log
        target: /rescore/log
    environment:
      RESCORE_CRON_SCHEDULE: "0 9 * * *"
      MYAKU_CRAWLDB_HOST: crawldb
      MYAKU_CRAWLDB_USERNAME_FILE: /run/secrets/crawldb_crawler_username
      MYAKU_CRAWLDB_PASSWORD_FILE: /run/secrets/crawldb_crawler_password
      DEBUG_LOG_MAX_SIZE: 200000000  # 200mb
      INFO_LOG_MAX_SIZE: 20000000 # 20mb
    secrets:
      - crawldb_crawler_username
      - crawldb_crawler_password
    networks:
      - crawler_net
  web:
    image: friedrice2/myaku_web:1.3.1
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
    volumes:
      - type: volume
        source: web_log
        target: /myakuweb/log
    environment:
      MYAKU_CRAWLDB_HOST: crawldb
      MYAKU_CRAWLDB_USERNAME_FILE: /run/secrets/crawldb_web_username
      MYAKU_CRAWLDB_PASSWORD_FILE: /run/secrets/crawldb_web_password
      MYAKUWEB_ALLOWED_HOSTS_FILE: /myakuweb_allowed_hosts
      DJANGO_SECRET_KEY_FILE: /run/secrets/web_django_secret_key
      DEBUG_LOG_MAX_SIZE: 200000000  # 200mb
      INFO_LOG_MAX_SIZE: 20000000 # 20mb
    configs:
      - myakuweb_allowed_hosts
    secrets:
      - crawldb_web_username
      - crawldb_web_password
      - web_django_secret_key
    networks:
      - web_net
  reverseproxy:
    image: friedrice2/myaku_nginx.reverseproxy:1.1.1
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
    volumes:
      - type: volume
        source: reverseproxy_log
        target: /nginx_log
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    environment:
      MYAKUWEB_HOST: web
      MYAKUWEB_ALLOWED_HOSTS_FILE: /myakuweb_allowed_hosts
    configs:
      - myakuweb_allowed_hosts
    networks:
      - web_net
  crawldb:
    image: friedrice2/myaku_mongo.crawldb:1.1.0
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
    volumes:
      - type: volume
        source: crawldb_datadb
        target: /data/db

      - type: volume
        source: crawldb_configdb
        target: /data/configdb
    environment:
      MYAKU_CRAWLDB_NAME: myaku
      MONGO_INITDB_DATABASE: myaku
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/crawldb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/crawldb_root_password
      MYAKU_CRAWLDB_BACKUP_USERNAME_FILE: /run/secrets/crawldb_backup_username
      MYAKU_CRAWLDB_BACKUP_PASSWORD_FILE: /run/secrets/crawldb_backup_password
      MYAKU_CRAWLDB_CRAWLER_USERNAME_FILE: /run/secrets/crawldb_crawler_username
      MYAKU_CRAWLDB_CRAWLER_PASSWORD_FILE: /run/secrets/crawldb_crawler_password
      MYAKU_CRAWLDB_WEB_USERNAME_FILE: /run/secrets/crawldb_web_username
      MYAKU_CRAWLDB_WEB_PASSWORD_FILE: /run/secrets/crawldb_web_password
    secrets:
      - crawldb_root_username
      - crawldb_root_password
      - crawldb_backup_username
      - crawldb_backup_password
      - crawldb_crawler_username
      - crawldb_crawler_password
      - crawldb_web_username
      - crawldb_web_password
    networks:
      - web_net
      - crawler_net
  crawldb_backup:
    image: friedrice2/mongobackup:1.0.1_4.2.0
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
        window: 10s
    volumes:
      - type: volume
        source: crawldb_backups
        target: /backups
    environment:
      DB_HOST: crawldb
      DB_USERNAME_FILE: /run/secrets/crawldb_backup_username
      DB_PASSWORD_FILE: /run/secrets/crawldb_backup_password
      DB_MAX_ALLOWED_BACKUPS: 7
      DB_BACKUP_CRON_SCHEDULE: "0 6 * * *"
    secrets:
      - crawldb_backup_username
      - crawldb_backup_password
    networks:
      - crawler_net

volumes:
  crawler_log:
  crawler_appdata:
  rescore_log:
  web_log:
  reverseproxy_log:
  crawldb_datadb:
  crawldb_configdb:
  crawldb_backups:

configs:
  myakuweb_allowed_hosts:
    file: ./myakuweb_allowed_hosts.txt

secrets:
  crawldb_root_username:
    external: true
  crawldb_root_password:
    external: true
  crawldb_backup_username:
    external: true
  crawldb_backup_password:
    external: true
  crawldb_crawler_username:
    external: true
  crawldb_crawler_password:
    external: true
  crawldb_web_username:
    external: true
  crawldb_web_password:
    external: true
  web_django_secret_key:
    external: true

networks:
  web_net:
  crawler_net:
