# Development overrides for the Myaku stack
#
# Overrides the image for all services with the dev tagged version.
# 
# The dev tagged version of the image for each service is built using the same
# Dockerfile as the prod versions, but the dev target is used instead of the
# prod target.
#
# The dev target builds the image expecting binds from the host to supply all
# needed files from the host instead of copying the needed files directly into
# the image. This means changes to the host files are then automatically
# reflected in the service containers without having to rebuild images.
#
# The dev tagged images are not publicly published and must be built locally
# using build_image.sh. Run build_image.sh with no args for usage details.
#
# Run docker stack deploy passing both the docker-compose.yml file and this file
# as -f args to run the Myaku stack configured for development.

version: "3.7"
services:
  crawler:
    image: friedrice2/myaku_crawler:dev
    deploy:
      restart_policy:
        condition: none
    volumes:
      - type: volume
        source: crawler_devdata
        target: /myaku/devdata

      - type: bind
        source: ..
        target: /myaku/src
    environment:
      # A cron schedule of "#" will comment out the line for the crawl job in
      # the crontab file so that it will not run while doing development.
      CRAWL_CRON_SCHEDULE: "#"  
      DEBUG_LOG_MAX_SIZE: 0
      INFO_LOG_MAX_SIZE: 0
  web:
    image: friedrice2/myaku_web:dev
    deploy:
      restart_policy:
        condition: none
    volumes:
      - type: bind
        source: ..
        target: /myakuweb/src
    environment:
      DEBUG_LOG_MAX_SIZE: 0
      INFO_LOG_MAX_SIZE: 0

    # Needed so that you can attach to pdb running in the container when
    # debugging.
    stdin_open: true
    tty: true
  reverseproxy:
    image: friedrice2/myaku_nginx.reverseproxy:dev
    deploy:
      restart_policy:
        condition: none
    volumes:
      - type: bind
        source: ./myaku_nginx-reverseproxy
        target: /run_files
      - type: bind
        source: ../myakuweb/static
        target: /www/static
    ports:
      - target: 80
        published: 8000
        protocol: tcp
        mode: host
  crawldb:
    image: friedrice2/myaku_mongo.crawldb:dev
    deploy:
      restart_policy:
        condition: none
    volumes:
      - type: bind
        source: ./myaku_mongo-crawldb/initdb.d
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./myaku_mongo-crawldb/run_files
        target: /run_files
  crawldb_backup:
    image: friedrice2/mongobackup:dev
    deploy:
      restart_policy:
        condition: none
    volumes:
      - type: bind
        source: ./mongobackup
        target: /run_files

volumes:
  crawler_devdata:

configs:
  myakuweb_allowed_hosts:
    file: ./dev_configs/myakuweb_allowed_hosts_DEVUSEONLY.txt

secrets:
  crawldb_root_username:
    file: ./dev_secrets/crawldb_root_username_DEVUSEONLY.txt
  crawldb_root_password:
    file: ./dev_secrets/crawldb_root_password_DEVUSEONLY.txt
  crawldb_backup_username:
    file: ./dev_secrets/crawldb_backup_username_DEVUSEONLY.txt
  crawldb_backup_password:
    file: ./dev_secrets/crawldb_backup_password_DEVUSEONLY.txt
  crawldb_crawler_username:
    file: ./dev_secrets/crawldb_crawler_username_DEVUSEONLY.txt
  crawldb_crawler_password:
    file: ./dev_secrets/crawldb_crawler_password_DEVUSEONLY.txt
  crawldb_web_username:
    file: ./dev_secrets/crawldb_web_username_DEVUSEONLY.txt
  crawldb_web_password:
    file: ./dev_secrets/crawldb_web_password_DEVUSEONLY.txt
  web_django_secret_key:
    file: ./dev_secrets/web_django_secret_key_DEVUSEONLY.txt
